<?php

namespace App\Services;

use App\Utils\Validator;
use Exception;


class UserService
{
    /**
    * MÃ©todo estÃ¡tico responsÃ¡vel por criar um novo usuÃ¡rio.
    *
    * @param array $data Conjunto de dados.
    *
    * @return array Response.
    */
    public static function create(array $data)
    {
        try {
            $fields = Validator::validate([
                'name' => $data['name'] ?? '',
                'email' => $data['email'] ?? '',
                'password' => $data['password'] ?? '',
            ]);

            return $fields;
        } catch (Exception $e) {
            return ['error' => $e->getMessage()];
        }
    }
}